name: Hello ISIS3710!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: date
        run: date
      - name: Say hello
        run: |
          echo "Hello ISIS3710"
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gitacionspai" #Must be unique in Heroku
          heroku_email: "mateoperez0508@gmail.com"